### ISSUE TITLE
[Mechanics] - Change locations

### ISSUE THREAD

**Issue by robertnitu02** [B-Zone-GTA-V/B-Zone-GTA-V-Tracker#494]

**Comment by SaRtORx** [comment]
savepos -> mechanics_blip_pos -> blip ID 637

savepos -> mechanics_duty&equipmentfinal-> NPC where the user can get clothes & equipment
savepos -> npc_vehicles_mechanics -> NPC used to get faction vehicles (PED https://wiki.rage.mp/index.php?title=File:Autoshop02SMM.png)
savepos -> mechanics_1 to mechanics_4 -> spawnpoints for faction vehicles
savepos ->  despawn_mechanics_vehicle -> checkpoint where mechanic members can despawn faction vehicles (same functionality that we have for paramedics)

NEW FUNCTIONALITY
savepos ->  deposit_vehicles_mechanic_players -> the place where mechanic members can deposit abandoned vehicles that they find in the city.

The user will be informed that the vehicle is in stored in this specific garage " Mechanic Deposit Garage " and they have to go in this specific place in order to get the vehicle back.

They will also have to pay a fee in order to get back the vehicle (10%) of the vehicle price

**Comment by robertnitu02** [comment]
We also need Mechanic Deposit Garage parking spots
